name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
jobs:
  deploy:
    steps:
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          customArgs: --dart-define="apiBaseUrl=${{ secrets.API_TOKENT }}"

