name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
<<<<<<< HEAD
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
=======

env:
  API_TOKEN: ${{ secrets.API_TOKEN }}

>>>>>>> 169ee8d3deda3067caec91599374b314dc06ec4a
jobs:
  deploy:
    steps:
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
<<<<<<< HEAD
          customArgs: --dart-define="apiBaseUrl=${{ secrets.API_TOKENT }}"

=======
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
>>>>>>> 169ee8d3deda3067caec91599374b314dc06ec4a
